# Default configuration file

# Defines how timestamps are parsed
date_format: '%Y-%m-%d %H:%M:%S,%f'
# Defines how restructured prefixes are formatted
prefix_output_format: '{timestamp} - {filename} - {user} - {message}'
# Define the regexes that will be used to parse each line's prefix
# NOTE: These are executed in order, top-down (ascending)
prefix_regexes:
  - '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<module>\S+) (?P<level>\S+) (?P<message>.*)'
  - '(?P<timestamp>.+) - (?P<module>.+) - (?P<level>.+) - (?P<message>.*)'
